name: Test Server
on: 
  push:
  schedule:
    - cron: "0 0 * * 6" # every saturday at 00:00 UTC

jobs:
    test:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install Dependencies
          run: |
            cd server
            pip install -r requirements.txt

        - name: Test Server (POSIX)
          if: matrix.os != 'windows-latest'
          run: |
            cd server
            python3 main.py --run &
            sleep 5
            killall python3
        - name: Test Server (Windows)
          if: matrix.os == 'windows-latest'
          run: |
            cd server
            python main.py --run &
            sleep 5
            taskkill /IM python.exe /F
