name: Test setup.sh

on:
    pull_request:
        branches: [ main ]
    push: #TODO: This is just for testing the workflow.

jobs:
    testSetupScript:
        strategy:
            fail-fast: false
            matrix:
                container: ['ubuntu:22.04', 'ubuntu:24.04', 'debian:bullseye', 'debian:bookworm']
        runs-on: ubuntu-latest
        container: ${{ matrix.container }}

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install sudo
          run: |
                apt-get update
                apt-get install -y sudo

        - name: Check that npm is not installed before setup
          run: |
                if command -v npm > /dev/null; then
                    echo "npm is already installed"
                    exit 1
                fi

        - name: Run setup.sh
          run: |
                chmod +x ./setup.sh
                ./setup.sh

        - name: Check npm installation
          run: |
                [ -s ~/.bashrc ] && . ~/.bashrc
                [ -s ~/.zshrc ] && . ~/.zshrc
                [ -s ~/.profile ] && . ~/.profile
                command -v npm
