name: Test setup.sh

on:
    pull_request:
        branches: [ main ]
    push:

jobs:
    test-setup-script:
        strategy:
            fail-fast: false
            matrix:
                container: ['ubuntu:20.04', 'debian:bullseye']
                include:
                    - container: 'ubuntu:20.04'
                      os: ubuntu-latest
                    - container: 'debian:bullseye'
                      os: debian-latest
        runs-on: ${{ matrix.os }}
        container: ${{ matrix.container }}

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Check that npm is not installed before setup
          run: |
                if command -v npm > /dev/null; then
                    echo "npm is already installed"
                    exit 1
                fi

        - name: Run setup.sh
          run: |
                chmod +x ./setup.sh
                ./setup.sh

        - name: Check npm installation
          run: |
                command -v npm
